import { GoogleGenAI, Modality } from "@google/genai";

const getAiClient = () => {
  // Using the environment variable as strictly requested
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  const ai = getAiClient();

  // Remove header if present (e.g., "data:image/png;base64,") to get just the data
  const cleanBase64 = base64Image.replace(/^data:image\/\w+;base64,/, "");

  // Determine mime type (default to png if unknown, though browser usually provides it)
  const match = base64Image.match(/^data:(image\/\w+);base64,/);
  const mimeType = match ? match[1] : "image/png";

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    // Extract image from response
    const candidates = response.candidates;
    if (candidates && candidates[0] && candidates[0].content && candidates[0].content.parts) {
        for (const part of candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/png;base64,${part.inlineData.data}`;
            }
        }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Error editing image:", error);
    throw error;
  }
};